### ISSUE TITLE
Texmaker for Windows

### ISSUE THREAD

**Issue by bokifide** [ancailliau/sans-indexes#2]
Hey!
I used your SANS 504 example to make my own index, but I can't seem to get it to work on Texmaker ;( . I'm using it on Windows, not sure if theres a different set of instructions perhaps? Looked online but can't get a grasp on it fast enough.

Boki

**Comment by dhondta** [comment]
Hi @bokifide 
I have no experience with TexMaker on Windows but I guess it works more or less the same way. While using the *Quick Build* option, this must be set up as of the command chain explained [here](https://github.com/dhondta/tex-course-index-template#compilation) (with executables' names adapted for Windows, I suppose).

- Did you adapt this command chain ? Or is this preciesly what does not work ?
- Also, did you use `main.tex`, `data.tex` and `main.idx` in the same folder before trying to compile your index ?
