### ISSUE TITLE
How to have the Index in a different order (non-alphabetical)?

### ISSUE THREAD

**Issue by hrbngr1** [ancailliau/sans-indexes#3]
Is there an easy way to put an index in a book order ex.  1-1, 1-2, 1-3, etc  vs Alphabetical? Can any of the data files be loaded into a spreadsheet be organized differently?

**Comment by ancailliau** [comment]
It is currently not supported. Feel free to propose additional feature to the index and/or additional tools that would help generating the index.

**Comment by mrodriguez911** [comment]
Are there directions for running script? I downloaded the program files and copied the SANS book to the same directory. When I run ./make.sh 401 i receive the following runtime errors. It appears I am missing some of the LaTex binaries?
   ./make.sh: line 10: makeindex: command not found
   ./make.sh: line 11: pdflatex: command not found
   mv: main.pdf: No such file or directory

This would be a very useful tool to get running.

Many thanks!

'rz'
